### ISSUE TITLE
Discard changes for one file discards all of the changes in mercurial

### ISSUE THREAD

**Issue by apieceofbart** [mrcrowl/vscode-hg#42] opened 2018-01-26 09:24 UTC
- VSCode Version:  1.19.2
- OS Version: Ubuntu 16.04 LTS

Steps to Reproduce:

1. Have a repo setup using mercurial
2. Add mercurial (Hg) SCM Provider from the Source Control menu
3. Make a change to two files
4. In the Source Control menu click discard icon next to one of the files
5. In the prompt window asking if you want to confirm discarding changes for this file click "Discard Changes"

Once you do this changes to all files are discarded.

Does this issue occur when all extensions are disabled?: Yes/No
When I open code with `--disable-extensions` flag I don't see any file changes in Source Control panel only message: "There are no active source control providers"

**Comment by mateatslc** [comment] 2018-10-10 18:58
Same here. Lost work in progress stuff several times because of this. Super annoying :/

**Comment by sergethompson** [comment] 2018-10-25 20:49
- VS Code Version 1.28.2

- OS Version: OSX 10.14 
This looks to be an issue that relates to .hgrc [alias] section where the log option interferes. 
By commenting out the below log section. I was able to stop the discard all problem from happening.
[alias] 
# log -f 
also #55 mentions an error having to do with a similar log conflict

**Comment by mateatslc** [comment] 2019-02-20 16:35
Indeed! I had the following in my `~/.hgrc`
```
[defaults]
log = --follow
```
Removing that cures the extension, too bad it hurts HG logs elsewhere.
Thanks for the tip @sergethompson!

**Comment by mrcrowl** [comment] 2019-04-26 15:26
Glad you guys found a workaround. Closing as duplicate of #55 for now.

**Closed by mrcrowl** 2019-04-26 15:26 UTC
