### ISSUE TITLE
Gutter status shows incoming/outgoing numbers as double the actual amount

### ISSUE THREAD

**Issue by MHHenriksen** [mrcrowl/vscode-hg#34] opened 2017-11-14 12:10 UTC
Running v1.2.2-3, but I think it's been a problem since I started using it.

For example, in a repo where I have 2 incoming and 3 outgoing changesets, the gutter will display 4↓ 6↑. 

It looks like it happens because I've extensively customized formatting in my .hgrc (well, mercurial.ini since I'm on Windows).  I recommend setting the HGPLAIN env var when the plugin invokes hg, see https://www.mercurial-scm.org/repo/hg/help/environment (and running vscode with this var set actually fixes the problem for me).

![image](https://user-images.githubusercontent.com/20283377/32778613-e1dd0ab2-c93a-11e7-9c44-75ab6680257a.png)

**Comment by mrcrowl** [comment] 2019-04-26 15:30
Duplicate of #39. Thanks for reporting.

**Closed by mrcrowl** 2019-04-26 15:30 UTC
