### ISSUE TITLE
SEEKING A NEW MAINTAINER / OWNER FOR HG EXTENSION

### ISSUE THREAD

**Issue by mrcrowl** [mrcrowl/vscode-hg#71] opened 2019-04-26 15:11 UTC
Hi users,

Sorry I haven't been very active in supporting hg in the past while. 

This extension was created when my team and I were using hg heavily for work. We are in the process of moving entirely to git. 

If there is anyone with typescript / javascript experience that would like to continue with maintenance and development of the extension (or fork it and start a new extension) I will provide full support including transfer/ownership of this repo. We can speak with vs code team about whether it is possible to also  transfer ownership of the published extension too, or alternatively I can be involved with publishing only. 

Please reach out if this sounds like something you would like to do.

**Comment by grinapo** [comment] 2019-04-26 16:43
This one showed up in the etension browser:
https://github.com/KristjanTammekivi/vscode-hg

**Comment by mrcrowl** [comment] 2019-04-26 23:04
Yeah, I’ve been in contact. But I think he’s in the same situation —>
moving to Git :/

**Comment by nsgundy** [comment] 2019-06-11 11:05
Hmm, interested in keeping this extension alive. Just not sure if reality lets me spend enough time on it to put a dent into the current backlog. Might have to give it a try for some time to see if its realistic?

**Comment by mrcrowl** [comment] 2019-06-11 20:54
Hey @nsgundy, thanks for the interest!  Is there something that you'd like to see done from the backlog?  I don't think there's an expectation that you have to do _everything_ on the issues list, although bugs are probably a good place to start.

Did you want to pick something and start with a PR?

**Comment by nsgundy** [comment] 2019-06-12 15:06
@mrcrowl Well, yes, bugs mainly.

Starting with a PR is probably a good idea.

**Comment by nsgundy** [comment] 2019-07-25 08:45
Um, well, as you can see, I haven't even started on anything yet.

**Comment by mklemarczyk** [comment] 2019-08-06 10:39
Hello there,

If you really need help. I'm able to continue work on the extension starting September 1st, 2019.

Best regards

**Comment by incidentist** [comment] 2020-05-21 17:37
I've got time and could take this over. Just submitted a (simple) PR for a bad bug, which got me familiar with the code. Seems like I could start with the existing PRs and see if others have done anything on forks that could be pulled in.

**Comment by incidentist** [comment] 2020-05-23 21:53
Hmm. I submitted another PR for a small bug but realized my first PR was on the master branch of my fork. I can redo them but if I could take over the extension, I'd probably just merge them as-is. I am also working on #30 .

**Comment by mrcrowl** [comment] 2020-05-24 00:06
Thanks @incidentist, this would be amazing. Let's work together on getting your PRs merged and then we can sort out access to the repro and publishing rights for vscode marketplace. I hope to look at these PRs later today.

**Comment by incidentist** [comment] 2020-05-24 06:04
@mrcrowl Great! Just pushed an implementation of #30 . Let me know what you want to do about repo access. I'm fine working on this one for now until/if the VSCode admins can switch over to mine.

**Comment by incidentist** [comment] 2020-06-01 21:05
@mrcrowl I created a couple more small PRs for bugs. Let me know if/when you want to move forward with changing ownership or co-ownership or whatever. 🚀

**Comment by hdpoliveira** [comment] 2020-06-14 17:22
Hi! I'm interested in this!
However I don't know anything abou Typescript or VSCode extensions, but I'm eager to learn :smiley:

@mrcrowl @incidentist  do you recommend a first issue? Or some documentation?

**Comment by incidentist** [comment] 2020-06-14 18:12
@hdpoliveira Great! I've only recently started working on this, and I think I took most of the easy bugs, but let's see...
#37 might be a simple fix.
#60 would be a good one if you're on Windows.

I found TypeScript very easy to pick up. The VSCode API is harder because there's a lot of it. If you want to try any of those bugs, we could hop on a video call sometime and poke at it together.

**Comment by incidentist** [comment] 2020-06-25 07:16
Questions for the room:
@hdpoliveira Do you want to be a co-maintainer of this project? You seem enthusiastic and very knowledgable about Mercurial, and I'm grateful to have someone to bounce ideas and code off of. 🍻 
@mrcrowl How do you feel about making @hdpoliveira a co-maintainer, if he's into it? Also, you're currently the only person who can package and manage releases. Are you okay continuing that?
@hdpoliveira @mrcrowl Now that I've merged shelve/unshelve stuff, my thought would be to release 1.6.0 after we merge PRs #91 and #88 . Does that sound good?
@hdpoliveira What do you want to work on next? I think #59 is high-impact but it's not sexy. I also want to work on #77 and #95.

🚀

**Comment by hdpoliveira** [comment] 2020-06-25 16:27
> @hdpoliveira Do you want to be a co-maintainer of this project? You seem enthusiastic and very knowledgable about Mercurial, and I'm grateful to have someone to bounce ideas and code off of. 🍻

Yes, I'd like that very much!

> @hdpoliveira @mrcrowl Now that I've merged shelve/unshelve stuff, my thought would be to release 1.6.0 after we merge PRs #91 and #88 . Does that sound good?

To me it does. Since #88 does not affect users, it could be left out of the version.

> @hdpoliveira What do you want to work on next? I think #59 is high-impact but it's not sexy. I also want to work on #77 and #95.

#59 I had trouble reproducing. If you can tell me how to reproduce I can work on it.
#95 is something we definitely need. @mrcrowl I noticed some PowerShell scripts in the tests repository, could you please explain us their purpose/how to use them?
I didn't open an issue for it, but I think we should implement automatic code formating and linting.
I want to work on #100 and #99.

**Comment by mrcrowl** [comment] 2020-06-26 20:45
Yup, I’m happy to continue doing releases. I could  carry out some testing for you beforehand. Give me a nudge when it’s ready. 

The only two things required to be release-ready are:
- Updating package.json version
- Updating CHANGELOG.mid

I package to a vsix file as well as publishing to marketplace. The vsix gets attached to the release in GitHub. This provides a manual rollback mechanisms for users if something gets broken by the release.

**Comment by mrcrowl** [comment] 2020-06-26 20:47
And just wanted to say a big thanks to both of you. Please to see this project being continued.

**Comment by mrcrowl** [comment] 2020-06-26 21:02
> I noticed some PowerShell scripts in the tests repository, could you please explain us their purpose/how to use them?

The purpose of these was to try and validate that hg responses, which the extension relies on, remain consistent over time. They are largely incomplete though and were only manual “eyeball” tests. 

There is potential to automate, with some effort. I would probably do away with the powershell though and just use node. 

The concept was to use a second local folder to represent the remote repository.

**Comment by hdpoliveira** [comment] 2020-07-05 21:02
@incidentist I'm filing issues left and right here 😄 
The ones I'm working on I'm putting myself as the assignee.
Feel free to pick any issue you'd like!

**Comment by hdpoliveira** [comment] 2020-08-03 03:01
@mrcrowl I think we're ready for version 1.7.0 🥳 🎉

**Comment by mrcrowl** [comment] 2020-08-03 06:57
[v1.7.0 released](https://github.com/mrcrowl/vscode-hg/releases/tag/v1.7.0) and published to vscode marketplace

**Comment by mrcrowl** [comment] 2020-08-03 06:57
Great work gents :D

**Closed** 2022-03-11 11:58 UTC
Labels: help wanted
