### ISSUE TITLE
Option to use bookmarks instead of branches

### ISSUE THREAD

**Issue by ajansveld** [mrcrowl/vscode-hg#10] opened 2017-05-26 01:08 UTC
Some of us use bookmarks instead of named branches in hg. Would it be possible to add a user option that uses a different command set for this type of setup? 

It would require changing just a few commands (mainly 'hg branch' and 'hg branches' to 'hg bookmarks') with some additional string parsing of the output.

Would be happy to help/test with this.

**Comment by mrcrowl** [comment] 2017-05-26 07:57
Good point @ajansveld 

Here's what I think would need to change:
- Extend "Update to..." command to include bookmarks in the list of "revs" that can be updated to.
- Add new command "Set bookmark" to set a bookmark on the current parent (show a warning if the bookmark is already set elsewhere, with option to force)
- Add a boolean `hg.preferBookmarks` setting to indicate whether user prefers to work with bookmarks over branches.
- Parse bookmarks from `hg summary`: when an active bookmark is present (e.g. has the `*` on it) and user setting prefers bookmarks, then show the active bookmark in the bottom-left of status bar.
- In the absence of a bookmark, show the branch name instead (or maybe fallback to hashes/revs)
- Allow push of multiple heads for same branch so long as they have distinct bookmarks
- The existing `hg.pushPullBranch` setting should probably apply to bookmarks as well:
  - when `current`, then only push active bookmark
  - when `all`, then push all bookmarks
  - when `default`, only push bookmarks on default branch (??not sure about this one)

Your thoughts?

**Comment by ajansveld** [comment] 2017-05-26 20:37
Thanks @mrcrowl, I agree with your proposal with the following additional thoughts:

> Extend "Update to..." command to include bookmarks in the list of "revs" that can be updated to.

To avoid confusion can we show bookmarks **instead** of branches/tags, not both? 

> Add a boolean hg.preferBookmarks setting to indicate whether user prefers to work with bookmarks over branches.

I was thinking of `hg.useBookmarks` to convey the intent, but either one works.

> In the absence of a bookmark, show the branch name instead (or maybe fallback to hashes/revs)

Would prefer not to show the branch name, again to avoid confusion. If there is no bookmark a combination of local/global rev id (e.g. `7173:bd40220086dd`) would be great.

**Comment by mrcrowl** [comment] 2017-05-28 06:30
Good feedback. Thanks.

**Comment by mmmmmtasty** [comment] 2017-06-07 10:07
This is exactly the feature I was just about to request, it matches my workflow of bookmarks over named branches as well. Just adding support for it!

**Comment by mrcrowl** [comment] 2017-06-08 10:24
@ajansveld, so I've been playing with this a little and had a question regarding this:
> _To avoid confusion can we show bookmarks instead of branches/tags, not both?_

Should an exception be made for the default branch? i.e. when you want to get back to the main trunk line?

**Comment by ajansveld** [comment] 2017-06-08 15:31
> Should an exception be made for the default branch? i.e. when you want to get back to the main trunk line?

I don't think so. In a bookmark-driven repo typically all development takes place on the default branch anyway, so there is no reason to surface that in the UI [1].

If someone does run `hg update default` for some reason, no bookmark is active so showing the commit hash seems like the right thing to do. This is actually a bad state to be in so it would be great to even highlight this (e.g. in red) on the status bar.

**Comment by mrcrowl** [comment] 2017-06-09 10:51
Progress update:
[x] Parse bookmarks from hg summary: when an active bookmark is present (e.g. has the * on it) and user setting prefers bookmarks, then show the active bookmark in the bottom-left of status bar.
- [x] Add a boolean hg.useBookmarks setting to indicate use of bookmarks instead of branches.
- [x] When useBookmarks, "Update to..." command will only include bookmarks in the list of "revs".
- [x] In the absence of a bookmark, fallback to hashes/revs
- [x] Allow push of multiple heads for same branch so long as they have distinct bookmarks
pushPullBranch:
- [x] when current, then only push active bookmark
- [x] when all, then push all bookmarks
- [x] when default, only push bookmarks on default branch 
- [ ] Add new command "Set bookmark" to set a bookmark on the current parent (show a warning if the bookmark is already set elsewhere, with option to force)
- [ ] Add new command "Remove bookmark"

**Comment by mrcrowl** [comment] 2017-06-09 10:52
Wondering: Should "Remove bookmark" offer to remove the remote bookmark immediately.  Otherwise there is no record of which bookmarks to remove on next push.

**Comment by mrcrowl** [comment] 2017-06-09 13:09
@ajansveld @mmmmmtasty I've got a version of the extension which you can install to see how the bookmarks support is looking so far.

To install:
1. Download the [.vsix file](https://github.com/mrcrowl/vscode-hg/releases/tag/v1.1.0%CE%B2) from the releases page.
2. In VS Code, go to the Extensions tab.
3. Click the ellipses and select Install from .vsix...
4. Select the .vsix file that was downloaded.
5. Restart VS Code.

**Comment by ajansveld** [comment] 2017-06-09 19:50
Works great so far! The only thing I noticed is that the in/out indicators are gone, i.e. it seems that `hg.autoInOut` is not working.

**Comment by mrcrowl** [comment] 2017-06-12 10:02
@ajansveld @mmmmmtasty another version to try here: https://github.com/mrcrowl/vscode-hg/releases/tag/v1.1.1%CE%B2
Changes:
 * The `hg.autoInOut` should work now. 
 * Pull is now limited to the bookmark name you are on when `hg.pushPullScope` == "current"
 * Using "Update to..." when the working directory is dirty now has a message to say why only a subset of bookmarks are visible (namely those on the current head).  This is because I treat an update to a bookmark on the current head as a "Set bookmark" (which can be done while dirty).
 
Let me know how you get on.

**Comment by ajansveld** [comment] 2017-06-13 00:40
Thanks! I noticed that after a Pull where the incoming changeset advances the active bookmark, there is no automatic `hg update` to bring the cloned repo in sync with the master. Should we include (an option to do) this? 

At the very least there I think there should be some visual indication that the bookmark is no longer current...

**Comment by ajansveld** [comment] 2017-06-13 14:18
Sorry, one more: once the extension has seen an incoming changeset, it stops refreshing so the indicator doesn't change if more changesets are added to the master (or the user runs `hg pull` manually).

Please let me know if you want me to raise this as a separate issue.

**Comment by mrcrowl** [comment] 2017-06-14 08:43
@ajansveld can you step me through a repro for that last issue?  I think a new github issue a probably a good idea in this case.

**Comment by mrcrowl** [comment] 2017-06-14 09:05
Think I've tracked the cause of what you're describing.  `hg incoming` doesn't include the remote bookmarks unless you use the `-B` option flag.  But then `-B` only includes the hash-code for each remote bookmark, so I'll need to run `incoming` twice if we still want to show a count of how _many_ incoming changesets there are.  
i.e. To get an accurate changeset count when pushPullScope == 'current', then I think it'll have to be something like:
 1. `hg incoming -B` --> outputs incoming hash per bookmark
 2. if hash for active bookmark from (1) doesn't match local then something like `hg incoming -q -T "{node}:{p1node}:{p2node}"` to get revision details (build a node tree? eeek)

How important is the count of incoming changesets vs. just knowing there are incoming?

**Comment by ajansveld** [comment] 2017-06-14 20:17
I suppose the count isn't that important, would you then also remove the incoming/outgoing counts from the status bar and tooltip to avoid confusion (since this affects the outgoing count as well)?

**Comment by mrcrowl** [comment] 2017-06-17 13:12
[Another version available](https://github.com/mrcrowl/vscode-hg/releases/tag/v1.1.2%CE%B2) for you to try @ajansveld.

**Comment by ajansveld** [comment] 2017-06-18 01:25
Fantastic! Great that you managed to implement the actual incoming/outgoing count for the active bookmark. I found that it doesn't always work when there are also incoming changesets for other bookmarks; if you append the following lines to [incoming.ps1](https://github.com/mrcrowl/vscode-hg/blob/fcb92695bdb1361451330f9180ee2756224edc82/test/bookmarks/incoming.ps1) we see no incoming changes in the status bar when we would expect to see one:
``` powershell
Set-Location $local
hg update 0 > null
hg bookmark "lotr"
```
Also noticed that hg.autoUpdate and hg.autoInOutInterval work but are not yet shown as valid settings.
Otherwise this looks great!

**Comment by mrcrowl** [comment] 2017-06-18 01:43
Nice find... some dodgy use of /g flag for regex.  Fixing.

**Comment by mrcrowl** [comment] 2017-06-18 05:48
Released as v1.1.3.  Thanks for your help @ajansveld

**Closed by mrcrowl** 2017-06-18 05:48 UTC
