### ISSUE TITLE
Version control tab doesn't show any file

### ISSUE THREAD

**Issue by pasqui23** [mrcrowl/vscode-hg#63] opened 2019-01-09 16:27 UTC
The output of `hg status` in the terminal shows that I have lots of file ready to commit,but the version control tab shows no files at all

![screenshot_20190108_131437](https://user-images.githubusercontent.com/6931743/50912199-7aebd000-1429-11e9-9df1-9e447ebf5ab5.png)
Neither filtering by `hg` nor by `mercurial` gives me any results in the developers tools

**Comment by pitaj** [comment] 2019-02-10 21:51
In case anyone arrives here first, I made some instructions on how to implement a fix for this issue:

https://github.com/mrcrowl/vscode-hg/issues/65#issuecomment-461638183

**Comment by mrcrowl** [comment] 2019-02-11 18:26
Duplicate of #65, which is now fixed.  Again, sorry for the delay in addressing this critical bug.

**Closed by mrcrowl** 2019-02-11 18:26 UTC
