### ISSUE TITLE
Unable to diff files in latest VS Code.

### ISSUE THREAD

**Issue by eigenbom** [mrcrowl/vscode-hg#35] opened 2017-11-23 00:04 UTC
Command palette 
> Hg: Show file history
> Select revision
Get the error: "Unable to open '<file>.cpp (#7141 vs. local)': Unexpected token f in JSON at position 2."

After some digging I found the string "97f25e8aa98c669e6f26ea2efa090e55da3583a0" is being passed to JSON.parse() in fromHgUri().

Visual Code: 1.18.1
Hg Extension: 1.2.3
Hg:  3.7.3

**Comment by BlackZork** [comment] 2017-11-27 16:42
Confirmed on current ArchLinux:
Visual Code: 1.18.1
Hg Extension: 1.2.3
Hg: 4.2.2

**Comment by Goodwine** [comment] 2017-12-06 21:29
I wonder if this causes gutters not to show given [this](https://github.com/mrcrowl/vscode-hg/commit/f018b7fcb8e5b906d54042f35a55706345b17e4d) commit that fixes #31

**Comment by vincg** [comment] 2018-01-25 13:11
bump - same issue here with Linux Mint. Is this being worked on?
VS Code: 1.19.2
HG Extension: 1.2.2-3
HG: 3.7.3

**Comment by tlourey** [comment] 2018-02-01 08:35
same here. seen it for a while actually in a few VS code versions. Currently: 

VS Code: 1.19.3
HG Extension: v1.2.2-3
HG: 4.3.1

**Comment by peacetara** [comment] 2018-02-21 21:44
I may have this fixed for Python files, in my repo: https://github.com/peacetara/vscode-hg
At least it seems to work for me now. 
It also fixes a problem I was having with pylint not working right.

I don't seem to have eslint laying about, which seems to be the original reason for toHgUri() existing in the first place.  If someone wanted to turn replaceFileExtension false and try, it may not be needed anymore, as it def. isn't for python linting or diff.

**Comment by nsgundy** [comment] 2018-05-24 09:43
Having the same issue.

VS Code 1.23.1
HG Extension: 1.2.3
HG: 4.4.2

**Comment by cbsom** [comment] 2018-11-19 14:56
Same issue on both WinX and OSX.
This issue has been around a while.
VS Code: 1.29.1
HG Extension: 1.2.3

**Comment by incidentist** [comment] 2020-06-14 18:32
Fixed in 1.5.1.

**Closed by incidentist** 2020-06-14 18:32 UTC
Labels: bug
