### ISSUE TITLE
Add ability to revert a single change block.

### ISSUE THREAD

**Issue by Eduard-gan** [mrcrowl/vscode-hg#68] opened 2019-04-06 17:18 UTC
Hi!
Currently with Git it is possible to revert a single change, but with mercurial it isn't. 

I found this feature to be so crucial to me that i lost my ability to use entire IDE for mercurial-based projects. That would be really nice if this would be implemented in future releases. Thanks!

**Comment by mrcrowl** [comment] 2019-04-26 14:52
Duplicate of #38

**Comment by incidentist** [comment] 2020-07-03 06:34
Re-opening this (if re-opening is a thing in GitHub?). This is about reverting chunks, whereas #38 is about committing chunks. Committing chunks would be very difficult, but reverting chunks is possible. The git extension doesn't use git at all to revert chunks, it all happens in code. We can do the same. I'll give it a shot.

**Comment by hdpoliveira** [comment] 2020-07-03 19:35
I believe this is already supported. You can click on the gutter for the change, then right click the deleted line and click Revert change.

Maybe what is being asked is the same as #78 - a button to do the same action?

**Comment by hdpoliveira** [comment] 2020-07-03 19:36
We don't support reverting the change for the added lines, though.

**Closed** 2020-07-12 01:00 UTC
Labels: enhancement
