### ISSUE TITLE
Plugin not recognizing repros on Ubuntu (works on OSX)

### ISSUE THREAD

**Issue by oursoc** [mrcrowl/vscode-hg#58] opened 2018-09-21 18:27 UTC
I have copies of the same repo on Ubuntu and OSX. I use VSCode on both. The Hg plug-in recognizes my repros on OSX, but not on Ubuntu.

I have no idea how to start debugging this. Any pointers would be helpful.

**Comment by mrcrowl** [comment] 2019-04-26 15:36
Sorry, I realise this is a really old issue now. 

Do you know whereabouts is hg installed for Ubuntu?

Does the hg log windrow report anything? (Under output panel)

**Comment by hdpoliveira** [comment] 2020-07-13 12:33
We now have tests running in Ubuntu, and also a warning when the tool did not find Mercurial installation instructing the user on how to proceed.

@oursoc can we close this issue?

**Comment by 1point618** [comment] 2020-07-13 17:52
Funny enough I came here to report this same thing. Mercurial is installed and apparently being detected, and `default` is set in the repos' .hg/hgrc files, but the extension doesn't recognize that and gives me a pop-up which sends me to the local user hgrc file.

**Comment by incidentist** [comment] 2020-07-13 20:45
@1point618 Your issue sounds slightly different: the extension finds the hg executable but is not recognizing the paths set on the repo, whereas the original issue is about not being able to find the hg repo at all.

You can help us diagnose this by pasting the hg extension log here. To find that log, click `Show hg output` in the menu of the Source Control pane.

![Screen Shot 2020-07-13 at 1 43 49 PM](https://user-images.githubusercontent.com/587244/87351850-e4610900-c50e-11ea-9473-946df8c50e9e.jpg)

I was unable to reproduce either issue on a fresh install of Ubuntu 18.

**Comment by 1point618** [comment] 2020-07-13 21:39
I think I discovered the issue thanks to the logs there.

I had my source folder opened, which has multiple tracked repository folders inside of it.

I opened those as separate top-level folders in VS Code, it appears to be working now. 

Thanks very much!

**Comment by incidentist** [comment] 2020-07-13 21:41
Great! Given that, and that I can't repro the original issue, I'm closing this.

**Closed by incidentist** 2020-07-13 21:41 UTC
Labels: question
