### ISSUE TITLE
Doesn't work after update to VS v.1.31

### ISSUE THREAD

**Issue by volodyabilyk** [mrcrowl/vscode-hg#66] opened 2019-02-09 17:47 UTC
It cans recognize repository. But you can't do nothing with that. After downgrading to last 1.30.2 everything work fine. 
![image](https://user-images.githubusercontent.com/44863652/52524226-68bcb600-2ca3-11e9-90b3-0df92b140422.png)

**Comment by alxpub** [comment] 2019-02-10 14:33
![2019-02-10](https://user-images.githubusercontent.com/88756/52535010-9102ee00-2d51-11e9-9db2-88706fdbc24e.png)

**Comment by zerkms** [comment] 2019-02-10 20:51
I believe it's a dup of https://github.com/mrcrowl/vscode-hg/issues/65

**Comment by mrcrowl** [comment] 2019-02-11 18:27
Duplicate of #65, which is now fixed. Again, sorry for the delay in addressing this critical bug.

**Comment by mrcrowl** [comment] 2019-02-11 18:27
You can update to v1.3.0 in vscode for the fix.

**Closed by mrcrowl** 2019-02-11 18:27 UTC
